# Generated by Django 5.0 on 2023-12-23 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0002_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(verbose_name=0)),
                ('expense', models.FloatField(verbose_name=0)),
                ('quantity', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('order_type', models.CharField(choices=[('IN_DINE', 'IN_DINE'), ('TAKEAWAY', 'TAKEAWAY'), ('DELIVERY', 'DELIVERY')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField()),
                ('order_price', models.FloatField()),
                ('discount', models.FloatField(verbose_name=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordermodel')),
            ],
        ),
    ]
